website/config/routes.rb
Rails.application.routes.draw do
  resources :messages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :caretaker, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }

  post "/api/send", to: 'api#send_data'

  root 'welcome#index'
end

website/app/models/message.rb
class Message < ApplicationRecord
    reverse_geocoded_by :latitude, :longitude
    
    private

        def place_params
            params.require(:place)
            # .permit(:title, :raw_address, :latitude, :longitude, :visited_by)   TODO: security
        end
end

website/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    puts message_params

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:message, :location, :latitude, :longtitude)
    end
end

website/app/helpers/messages_helper.rb
module MessagesHelper
end

website/app/views/messages/_form.html.haml
= form_for @message do |f|
  - if @message.errors.any?
    #error_explanation
      %h2= "#{pluralize(@message.errors.count, "error")} prohibited this message from being saved:"
      %ul
        - @message.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :message
    = f.text_field :message
  .field
    = f.label :location
    = f.text_field :location
  .field
    = f.label :latitude
    = f.text_field :latitude
  .field
    = f.label :longitude
    = f.text_field :longitude
  .actions
    = f.submit 'Save'

website/app/views/messages/edit.html.haml
-request_params = {"dev_id": "atenne", "confirmed": false, "payload_raw": Base64.encode64('{"response": 17, "time": 1800}')}
- url = Message.last.downlink_url
- JSON.load `curl -H 'Content-Type:application/json' -H 'Accept:application/json' -X POST #{url} -d '#{request_params.to_json}'`

%h1.tc.mt2
    NOTIFIED

website/app/views/messages/index.html.haml
.row
  #deadhumans.col-md-6
    %h2 Notifications
    - @messages.each do |message|
      .message-item{id: "message-#{message.id}"}
        .row
          .col-sm-9.message-colored-item
            = link_to "#{message.message}", message, class: "title"
            %br
            = time_ago_in_words(message.created_at).to_s + " ago"
          
  .col-md-6
    #map-overview
%br

:javascript
  var mymap = L.map('map-overview').setView([52.090736, 5.121420], 8);
  window.map = mymap;

  L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=sk.eyJ1IjoibG9zb3MiLCJhIjoiY2pueXhwZ3RvMDFzdzNrbXFicnlmY3Q1YiJ9.ixxDbuWyXhWX4PY4qt07ZA', {
      attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
      maxZoom: 18,
      id: 'mapbox.streets',
      accessToken: 'your.mapbox.access.token'
  }).addTo(mymap);


  var redMarker = new L.DivIcon({
    className: 'help-marker red',
    html: '<div class="help-marker-inner"></div><div class="help-marker-inner2"></div>'
  })

  var orangeMarker = new L.DivIcon({
    className: 'help-marker orange',
    html: '<div class="help-marker-inner"></div>'
  })

  var yellowMarker = new L.DivIcon({
    className: 'help-marker yellow',
    html: '<div class="help-marker-inner"></div>'
  })

  var data = #{raw json_escape(@messages.to_json)};

  var markers = [];
  for(var i=0; i < data.length; i++) {
    latitude = data[i]["latitude"];
    longitude = data[i]["longitude"];
    if(longitude > 1 && latitude > 1){
      markers.push(L.marker([latitude, longitude], {icon: orangeMarker}));
    }
  }
  for (i = 0; i < markers.length; i++) {
      markers[i].addTo(mymap);
  }

-# var lc = document.getElementsByClassName('leaflet-control-layers');
-# lc[0].style.visibility = 'hidden';

website/app/views/messages/new.html.haml
%h1 New message

= render 'form'

= link_to 'Back', messages_path

website/app/views/messages/show.html.haml
%p#notice= notice



= link_to '< Back to notifications', messages_path


%h2 Details

%p
  %b Location: ...

%p
  %b created_at:
  = @message.created_at
%p
  %b updated_at:
  = @message.updated_at

%p
  %b longitude:
  = @message.longitude
%p
  %b latitude:
  = @message.latitude

%p
  %b Downlink_url:
  = @message.downlink_url
%p
  %b App_id:
  = @message.app_id
%p
  %b Dev_id:
  = @message.dev_id

%p
  %b level:
  = @message.level
%p
  %b pain:
  = @message.pain
%p
  %b bodypart:
  = @message.bodypart
%p
  %b cause:
  = @message.cause




-# # Message(
-# #     # id: integer,
-# #     message: string,
-# #     location: string,
-# #     # created_at: datetime,
-# #     # updated_at: datetime,
-# #     longitude: float,
-# #     latitude: float,
-# #     downlink_url: string,
-# #     app_id: string,
-# #     dev_id: string,
-# #     level: integer,
-# #     pain: integer,
-# #     bodypart: integer,
-# #     cause: integer)



#map-show

%br

-# %link{:crossorigin => "", :href => "https://unpkg.com/leaflet@1.3.4/dist/leaflet.css", :integrity => "sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA==", :rel => "stylesheet"}/
-# %script{:crossorigin => "", :integrity => "sha512-nMMmRyTVoLYqjP9hrbed9S+FzjZHW5gY1TWCHA5ckwXZBadntCNs8kEqAWdrb9O7rxbCaA4lKTIWjDXZxflOcA==", :src => "https://unpkg.com/leaflet@1.3.4/dist/leaflet.js"}

-# = image_tag "http://maps.googleapis.com/maps/api/staticmap?center=53.20393,6.52751&markers=53.20393,6.52751&zoom=7&size=640x400&key=nBxnglIWacwoX3XNZapZcxP9Orw="
-# = image_tag 'http://maps.googleapis.com/maps/api/staticmap?center='+@message.latitude.to_s+','+@message.longitude.to_s+'&markers='+@message.latitude.to_s+','+@message.longitude.to_s+'&zoom=7&size=640x400&key=nBxnglIWacwoX3XNZapZcxP9Orw'

= link_to '30 min helikopter', edit_message_path(@message)


:javascript
  var mymap = L.map('map-show').setView([#{@message.latitude}, #{@message.longitude}], 13);

  L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=sk.eyJ1IjoibG9zb3MiLCJhIjoiY2pueXhwZ3RvMDFzdzNrbXFicnlmY3Q1YiJ9.ixxDbuWyXhWX4PY4qt07ZA', {
      attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
      maxZoom: 18,
      id: 'mapbox.streets',
      accessToken: 'your.mapbox.access.token'
  }).addTo(mymap);

  var redMarker = new L.DivIcon({
    className: 'help-marker red',
    html: '<div class="help-marker-inner"></div><div class="help-marker-inner2"></div>'
  })

  var orangeMarker = new L.DivIcon({
    className: 'help-marker orange',
    html: '<div class="help-marker-inner"></div>'
  })

  var yellowMarker = new L.DivIcon({
    className: 'help-marker yellow',
    html: '<div class="help-marker-inner"></div>'
  })

  var markers = [];
  markers.push(L.marker([#{@message.latitude}, #{@message.longitude}  ], {icon: redMarker}));

  for (i = 0; i < markers.length; i++) {
      markers[i].addTo(mymap);
  }




-# var pointerIcon = L.DivIcon({
-#       className: 'help-marker',
-#       html: '<div class="help-marker-inner"></div>'
-#   })

-# var lc = document.getElementsByClassName('leaflet-control-layers');
-# lc[0].style.visibility = 'hidden';